---

- hosts: all
  become: true
  tasks:

  - name: uppdatera repository index
    apt:
      update_cache: yes
    when: ansible_distribution in ["Debian","Ubuntu"]

  - name: installera apache till servers
    apt:
      name: apache2
      state: latest
    when:ansible_distribution == "Ubuntu"

  - name: lägg till PHP support för Apache2
    apt:
      name: libapache2-mod-php
      state: latest

  - name: uppdatera repository index för Centos
    dnf:
      update_cache: yes
    when: ansible_distribution in ["Rhel","CentOS"]

  - name: installera apache till servers med Rhel & Centos
    dnf:
      name: httpd
      state: latest
    when:ansible_distribution == "CentOS"

  - name: lägg till PHP support för Apache2 Centos
    dnft:
      name: php
      state: latest
