---

- hosts: all
  become: true
  pre_tasks:

  - name: installera uppdateringar på CentOS
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: installera uppdateringar på Ubuntu
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: workstations
  become: true
  tasks:

  - name: installera Unzip
    tags: unzip
    package:
      name: 
        - unzip

  - name: installera terraform
    tags: terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root

- hosts: web_servers
  become: true
  tasks:

  - name: installera apache till servers Ubuntu
    tags: apache, apache2, ubuntu 
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: installera apache till servers centos
    tags: apache, centos, httpd
    dnf:
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"

  - name: kopiera html-filen till servers
    tags: apache, apache2, httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644 



- hosts: db_servers
  become: true
  tasks:

  - name: installera MariadBe till servers CentOS
    tags: centos, db, mariadb
    dnf:
      name: 
        - mariadb
      state: latest
    when: ansible_distribution == "CentOS"

  - name: installera mariadB till servers Ubuntu
    tags: db, mariadb,ubuntu
    apt:
      name: 
        - mariadb-server
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:

  - name: installera samba till servers Ubuntu och Centos
    tags: samba
    package:
      name: 
        - samba
      state: latest
