- name: lägg till SSHnyckel för simone
  authorized_key:
    user: simone
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAFFpWePY73lU3AzS80CD05o+GAWl8Im5HUBaOETRaJA ansible"

- name: generera sshd config filer från mall
  tags: ssh
  template:
    src: "{{ ssh_template_file }}"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart_sshd
